language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3.5"
install:
  - "pip install -r test_requirements.txt"
  - "pip install ."
script: "py.test --cov=ssh_certificate_parser --cov-report=term-missing -v tests/"
