name: 'CI'

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pythonversion: ['3.6', '3.8', '3.8', '3.9', 'pypy-3.6']
    steps:
      - uses: actions/checkout@v2
      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.pythonversion }}
      - name: install dependencies
        run: |
          python -m pip install -r test_requirements.txt
          python -m pip install -e .
      - name: lint with flake8
        run: flake8 ssh_certificate_parser/ tests/
      - name: test with pytest
        run: pytest --cov=ssh_certificate_parser --cov-report=term-missing --cov-fail-under=60 tests/
